apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:sY2uwEO4QWkSgvJF3wZMf2V2uGYiT24oqbABzcSYC3zgmrIkx/3hzVDXwiDm1t/oy6xhud5txqVuin6r5mvRG2aE2fw9tt90g6W8Ft8ThRoqzaH7vh0DrCV3+nbypKptG2d9TUi+QAQqj2CI0+90/g1rWUhdRrvFSvNycmKYq2A1eAxUnrh9CHkretaX9SFxj6uQ/+N0/HHGG30jgArnBLXrA4/QsdhSC24G4j3WaaFbUAu6Ym/BUb/LLvCOuEccP/QORmsNm8XsVMabTLc1nPiYq2cVdA7aAymq1l3GpnsGnm6WtZUFW7F9sgFWfRyCz7JSKeMupGco5+dsm1xOrfbLRxCB8ZvstHMnlyA4YlMGK2UTks+w1oaVFUT0lEKO,iv:xVGRrLPemTHU/78b7fNe7EIrp5GzdkbK/aY7aqks9IA=,tag:JEhJm9sxlav93/GbdeKqKw==,type:str]
    identity.pub: ENC[AES256_GCM,data:oVt3sZDuC6ghbmgBzrgryAJR4aH/Cqawe+til7TqhSQTgPMh7RU1G5x1iFhwLGPPZvE3T47LUrQNDsOCDOCXF+zjJLllsCf9I2BHnjmUwrNNQTUy+MkEu+Am1DlCj+xO9ZApnhy8KP9tsSEfn183vorURF3NQn92BxHYA4nQbggqtMa381MTIcIgyJsz1xfkrjuxlCZCWFOkJzOm35yEuBJsqZNrWoN+C0daDxIK98FQn3x3w70rVRygK8+WRfb8q43FaVuWCjBNeL4LTw==,iv:JgCIM/gEw3aesXD/FAa4TM7mlNwXboutlKb/By1pfXk=,tag:/Wi2Urc+p6mZd4F8J/pDYw==,type:str]
    known_hosts: ENC[AES256_GCM,data:RuKhZ67cXMouYbweFBcB+GmDvVYesorsk0r4xVK3Wp9rozSq01ftcJT7XDwzQnsXRueOyiAdwBBflmqDjKkUrjOQBxhCbdBwiu1Sjpbhzeq9kAciGwKSjNQusqn6pbqSYQWwvWjyNlcYnwYU+fke2/c2NF3VcyQokPhTpGMn5wmKUBsFY85u029SZZ8TnfPBcZxYIL9NRzo3k1bSBPYNPG0u+CxtkXpopWth,iv:YpnJi+zuTtTP50iI5Uff4T/XdbhCIwyW8Kiwk5ARUDo=,tag:IeBLixtEDO+tcyKXehb1Og==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1n9xvc8p6crcha6nylpszt2cq2ywpgejy0unjy268hjx566x98c9qfp68my
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1UHA5RTQzSGs5R2p2b0cv
            SE5saVJrVFlOeFlwM2E0bTRDTVBEZ2JrWVZFCm5zZXlseEtYSUlsTXg3Q2dZRjU2
            WEd0VVEreW5JTVoyRlNUM0JNbVM2bTQKLS0tIEFKVUExQkVKQkI5aExpdkdta0Er
            NVVpMWd6bVM3VmhyVGJFOFRYUnVNcWcKC7/UNFOBoBLOAgmsh7ZBM68rEk4SUijY
            2KeldP488YDnImEomWW7dwN2q8QIxIbTR8Hypsc0qhhDZqmKYGssDA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-02T00:38:57Z"
    mac: ENC[AES256_GCM,data:WO+im8i7+ahpksFd7BAW/YKxD5vE8d5MFGMRD3wZZDSs1Os03vesoj6j8VTuYZDfoHh43pB8nkrL3KSU4XjkUevaIRcHGirHiDai5yQR5lA0I8aa2nm9a7/D6td5XHJSeOPenP1Oe1cOEnRspWJg6p/svwhqxrvBU8iK8/7FLeI=,iv:J9+kKhgh/TRH4ej3zz3WCYjTqWGkJtlv5Vu3JNZYgP0=,tag:Td1/5lkfOOZrdZwhX9vt5w==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
