apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:Q2cjuWuzESPBkytCxe/CR/PEcloGFDNxWurhQiF6c+Cia5byABt/LBcVtvl/819ktP5e6ODdwNgm59LEea9hn4dknV+Abegf055MV17gvpaKQGm4CotSK4pi3xZAFX4CU6t3O2IPbnTn0gjAejIm3ahA7amMmbIRGJV/TKrmByzEoFtXzmcOGlgAfE3ayW+dyMl4aloyxlet/pkDpW1xuB960FeC3aAnpQI6Bju4CwVSydsqKvIkRn7DqSUZXmqCHYwGQphC+bWNrfMTw9qBdm9KOxQ8z1QoFbPl8bQcO80GoCsg/xYMJHuP91s/AQoW1h6xN3GYKW51P/WIZw6cYZzMjKFWaJis0dPdzuOdTPH2YT+ypOP3Nqk7Sfcd9dvP,iv:ewN47cKE1+rjHsPXYzEsHFZbLaFt78h3ZrVHY0shauQ=,tag:LpzjWYJiOtNeSFrvAkp3vQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:6ZbAZ5IFYZgpIZa+bRLByoYmAL8tApejC+FClIxvzBoWYdLdt09DeQtZnhGqBqPBUZycj5K9gc2lhtq0HGgRJ640MfymOkioekFT0ALBClD3+47+lAC8wy0N4wQFnoy8ty9MAhf9Fsi3b7mp5QSAmmljtG6btiN/RrTsTbtXgV8QSBHBmWACOWGUiwZR3Q3gveNnmbrAbbdLy04GB0KkGH+zQMUINB+42CUv4VJOuIPTtFMwWJ2ijovvrLLHhHVgwPPtUVT/Aktfv0p4Xw==,iv:+EhiOYoFQhb+9WQNWRpQy73iznMST0xsLVzocvP0/aU=,tag:xKUpkj0PaKSvxbab8fJx3w==,type:str]
    known_hosts: ENC[AES256_GCM,data:fN26/iD/jKbhPwQURmseJRwfKvAoSVkhc0joxUqtXZ6vVeRUJxqlvTYTAOc6AP1VX5KLEf1+QaEhZoVv8Ne8ZF/iUqnGze8rvI23gR+VDiAfY6Xk7sCPn3qrm0vCFjFXhAQxSvCAAECyKAw6YdBZJFyIcleZqDUb/sB+o66L1rYC7KAx6G+0ueVWGZGUm8tquXxYiV7rCW9HJYGzqNQQKw0JvtiSa5XyCoFd,iv:J6cY62l07cSidNMGHATx53iuNlL0589s1Gxa9KsvHIA=,tag:o/DPwzRukgJYf88KOGhLhQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1n9xvc8p6crcha6nylpszt2cq2ywpgejy0unjy268hjx566x98c9qfp68my
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2SXVDNXhiUGNINXVFaDZh
            Qi83Zmt3RWJ2eFN4NjVKSW9EMHdtdUIxVERvCkZhenpWMnR1dHUyZzVPWWhkVUtC
            aHl6VXhiSkEzbjJGdXpkcnFNWDNDamsKLS0tIHNkR2NnOUY2aVREQ1F2dlJRRzFB
            bllJei9DamNFVUxxOVRuRTkxcnJZYm8KMfjyskk/wUO2khfT9FCZvMArvkje5gF1
            cKt38t8UyM5TUqpM4FLOhZLB/55LM6QWok/JLw5GS5MCJWbNmizzOw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-02T02:21:39Z"
    mac: ENC[AES256_GCM,data:lGleqmi0OA5tRoVSm+x+0iroQ3vLkSku0TL5SqeohMe7XVyYq0E+21L35JEDMq6DvVExhXJMgG+4vtRTmKgo1L9zGAJ1LXdKbKyYRU8ltCkKRqRy3kzZSxi3IwMG9bhhsKD5d3DCS/g52PdGV7xgi3J0C1ERg+dGlTPttkFqJJ4=,iv:eRSncHT2Pn1V47VdUPJqWj05x98lQ1ZOsEUmUUXEEIg=,tag:6yWP3ju314ox2UE37Vgr3Q==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
