apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:nv2nBGp9pumpjD94byoZx0nAzzkNuaMNBFiVAR9UkSDJAgWOq5J3pm7y2kbcNiNxjkOXHJ06RI6rvDBiTcnPZ0gqKuqLS2JuARhBYhyM8kAQ9Y2OOxqSfION5F30+AJ1eEMf0D5wfnXB43+EftIDrTiPiQQaV6PM5tzlM85wFLtUOW+DaP1kJo81f0n59v1+XkyqeXMpUBbKSh7kGjUrzc/tkvx1nQbNtnpVXPdtuQ7Xrr5fTfAOT/tg0HkTlScDYuI5rxKtC8g1pCBVtEv7+Dm43rC6o9yBsHb/XlKxS19WoM4PSTD9VTjxXgvR7MkZsTDIknJtvd7icNySVIulOrPoxMh8AeEXH9cfPviKsWenmrGVzPcU/UBZnlNAQn6m,iv:AeFGPwz/H9uzXb9GzbuI73GeuS0x2Gpm18PE9HsUN58=,tag:HkByzpDhl+p7fmmD1V6Leg==,type:str]
    identity.pub: ENC[AES256_GCM,data:eokbcKCbRXDKLwCJI5KpKhhzZw+CSdlTvE/lg7GOGMJPziBUVgdxtDCW/1gD7dBhqfh/JA/kDq8m1+a7dzHnnIs42tNJqXmCYi8atB5RvJ2SEWI8XtlueTsAU3wDTeuMMFkGlMU04gWyZQtZCprQZMs6sR9G0sQQr/tT01tt9t0yKTFj9vOAuwG6cp49cVIn7EjA3akME5aqMgiCGK9bFQkuh8qgY7QuRK+573z9ECnzjMNJ15TgIFVb6Hq/fXQ+iWmS4vovtV/cVkQhLA==,iv:LTwMoYTK9mFWPBFqD4FELDnP2r7i9ZEoNGI1Rlrx5Ho=,tag:6sXohHC6V3N73je9xAAhAA==,type:str]
    known_hosts: ENC[AES256_GCM,data:1Zmu6eCUF1dn8acB4Ko/NFsF8SV1Z196DD5fjTqBqFBCB/Pwsf3WroR9VmuNc7e9DkGkzFTsnEwsVk9XjiFBWdiaZwKD9s7q0ny1QG7Db2A2VIqkRFWwFEuDpaCsZkBQKKzZkc0G6EsjXt/s69JiReYPaZUuFlTCkFqqoOuZsVUElXUoqePMk/uHBAFkOKbwnCAtXAAbMMhA3Gb4iCZERVV4GE9Ceq1tbWjg,iv:JfY+Tmy39k0IWL0Smy9yxmD6IM9glPlpsUxtJwp50xw=,tag:bJLtuXpYWa63iUsBlp68zQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1n9xvc8p6crcha6nylpszt2cq2ywpgejy0unjy268hjx566x98c9qfp68my
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyOG1DZlJSSGhGQ3Z6aHVo
            ajBEVVNMOHdWZVB6b0NDYm90azY3d21oV213CmtYMjMrd1FNRUc1V1NOMUYwbjZk
            N2xNRERaZURvUTk5UWRBZXVqWjNJa3cKLS0tIDViR2ttMUFmc0RGVEY1c2gwcjI1
            TWlVTW9ZVUxFb3lkS2JxR3Q1RHR4RmcKxNA4jxoljDC5V+7EJbVYiraG9RjTQML8
            Tpaotf0U+nkvcBc30NAZS+XODr2Q7+u2UnA44IwjPQChCBoNrw3tjQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-01T05:34:30Z"
    mac: ENC[AES256_GCM,data:1g5BqaEB3noC6W//Dkl7FuTs8gecc396q9bMbar+AgKWerzmWuc1DSD8cR1WyTvBR+ce0N9lhMFcvIiTJrIS3dQcCl4LAqNbdjGoeNGYkFA1bsXSZRRr/CuTuIDwhDheS13riXmMNSLlphjI1kwecrOXwwNTsuE0eQx+FmB2mLc=,iv:33ahDqHPTGNbLdtKcEII2HCJpNQ89cMpuyUB2OF9VD0=,tag:mT9gVN/DWqDabztTmI7liA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
