apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:DP6Y+TNLWWgqpRL5v8T4+GWtSETKrF2dhUhiunDVqQsbFx+R0ZEnu4wx6p4tjrNkQe/dvzrw4mkagjJ7hUM8zW+SP7JX6HkXRKKfFgeJvNDiPN6UmxOgaAuL+MI07Lv6MjqdMvyeHGeHYe/TuSAbQ1V5qvoDjMsF+P3budsmZfX/2N+NoaiU9TofL8/EEMiQ4rTF24nPAvJsyYUsxBMwOsW0hKAaJcqMyUWNGo7Qm6x41MBK0aHuqWoeQ/sjOhqhpnnur9hypbRjQaK0Ddkg1Fi9sHG6qXVSUZdtK/iZVUsskzlgUqvfnRED9NKwryOdHGkWwiDaVInnxFCa4tMgBLaM5UxR2UubEkUdeRlyh0oETPuPCnfIQhvMkkPAffNl,iv:fgBzvt+G4UKXMS4Ou128OmFLV05A18gW2QSW+uXCXrc=,tag:kQLOWu2qBS8mtdSPyqgaBg==,type:str]
    identity.pub: ENC[AES256_GCM,data:9378j9Q+0W2dsEZFnIxWGlZcvwj/bn87VsnPg5cBZubga+tUvPCdtRiyJ1L3+s8fWZ7rj//gd++qpCOxd3xmlDHnbf2Pp0r8mYItAgKe/oi5hoA4icYxx0BxtL/Ue2q7LSvO0mLIqY2z4uWL++OsGEq1qWvOWZOl2jqY8l4MFxxgnzrWV0+dKOTDJyhU3uUxjpl7i36W/vbKR2eNLjyAQDCi3gHcsAUa2E7D2cq0xAWUvcsLC2IyvwaU2FUbCv0Njjj10EdHNBBAvbfF3A==,iv:RNe6nyB1uFfRIeBIof90DGOlLHLbr+vXdBst+bvRODE=,tag:UwersGRwfHX4s48SubVVZA==,type:str]
    known_hosts: ENC[AES256_GCM,data:Z7Gf0tbP4Tz3virNKPenr0GVVv+1y0tQTiwA0DwpnWD55/KUoqFMKcsGuDDudaSZbWJqsyoybeQ4ppDkfdLfXjm6Hon2Z5b1vKBdpXu9bi89dh479o1+43Ghm1/aSRYjVo89IWYfLtEbuDdrW8Zhpj3+G8DlE07lNEV4ySCx1TQqkJbS3qr0/tkAZWIM287oLcvNIafT+3rGd4Q9CTMWGX+GaYdkNE+8rtS0,iv:ujCpV9qpEa7Qq0AtIT/xaOR/YRDWXBnx+7eoYCT/RQg=,tag:y76WtLgNd2ihkYm1To6JRA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1n9xvc8p6crcha6nylpszt2cq2ywpgejy0unjy268hjx566x98c9qfp68my
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHR0tJclgvbTNwa3NtU0NN
            UStCN25Wa2dVaW5EWlhFY0dlM1lFUkVPSWx3CmhQdFVFV2xVM3l2L0R5VjFTeXFE
            WFRPOERTYnA3TzFRWVJLU1gxR3dLb2sKLS0tIEtmcWZ2MmRRbDAyMENTSnhhaXRU
            MnBhZmlhZDBBSExEZlFNMitjVFUveU0Kr3QC/xQoA9WPw0ux/wK38PuU2eqi9KzR
            vzLL2vAPn9S4735GYPaXRwS87g+b62t07bKpDsDGDjQnEpV4KnTzgA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-07T19:42:33Z"
    mac: ENC[AES256_GCM,data:/6KhH0TIjGBzOD74O5sxOIm7M7UBIz+dtVN79c8AoLg4tWVJtkK9YL1s1zWoDPST0AtHV3ZhM0JedXBuO5jhjztrH+Iej6y0x1phjmYFo7vCVoAKdLzQ5UEzP3ZKqk5AX2kWtDEUukrw2hFj5+dAPFx5qmYYbIfcKj7k2v3GlHE=,iv:6HKPdwdGdadefp1xIw2oTUMAH9MOHXMFlTTKYqiPvkw=,tag:QZCzD1o1jGV0AAOoJsfccw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
