apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:2DpFMtrKYvDE6qG07ooob/0uIXuoOXen8hofoO8J7NHfBJcov3W7shldEAt5/rX8BeJIzwQpjX0h+Mg3yo03T6ToJXnpLvILBkeCWu11uoeypSI/weSuox5fQ3UNyqdPPL0lEo4zXqbWXDAD+De+LwI76pJgj+8JfIFiSghXgzsUKIoLxUY4xWT7eRsw1dzxkVA5jb2x6322Swns5rI2Rgy0xDWEnNGxQeGzwlX1ziuVtId2LNHqghxLateciia3ueXUvFEO9qNNZXrvsbkmt+wHS/CPuTg5wg0sT1aO3rfHolNuK4TDLlsLUZWA0ipB/uHH6F9CrXtumA9w1cA/SZ+CbmSXKSIewTGls+6dIE6O1BUqAVElhNM2KreaP94X,iv:0ke9KlkyUlnwktmqfG5Txb9tg1iZCw5jSJyc57B1DxA=,tag:5O90F6pX9vPIMTeIM6kT1g==,type:str]
    identity.pub: ENC[AES256_GCM,data:+lkN/c/sc2JW1rHKo6JHDEXIRBpPAGwlgbDCoalLDWDh+7mSoTWlhWMAp9EDQkihAmO9e98oFctuU4BIo5L5MVBJhPNUMehvptS5poMnmDPgU4/Lk/f75hORz/e7VKl54d1rYV6nmCOWUK+leehtVRLd1+ZuL5rWY1KYPVpgdhNco4+VDoTrG5qZ7k6dETJX3e8HCkqgczU51MtMbUqcw5SEeSmcyZPi467ZN1ImzGzzmPhLu06PZPz314V37hWZiOSY6UdZL3oQG3N8Dw==,iv:FsKH+xwSKoUvnt6vmyHq7iCjiFMpftQc0gDARA75U0k=,tag:qg9vjWP6AQFj4W42xp/Xzw==,type:str]
    known_hosts: ENC[AES256_GCM,data:RvYr8vskbAKKNM9yVjRv/DVXKCSX57cUPdQ13A9Y3ItJn5U+3dv1egSGT9/8rLR+lyquUduBMkrXZKA3Zb3ZXTnjwetXftM+EvmZzI5OuKZGOuyeZ09cwbW9UY2lhGwlh5GQ0YOTrEJ8lx3yOsabaUVrI+1Xu2JI8iQnRD7Xy7ZPxkrwvbAmOcAEa9Zi2BC9r/gjLwJ1vPRwoICflvp2pdHUHdlf+3pVEeSK,iv:DyYYrJMKLNv5XQ2Y25/mKFFb+hdXlZSlb8q3drs1u6Y=,tag:iQyL4eSzETrHKWEBE65n1w==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1n9xvc8p6crcha6nylpszt2cq2ywpgejy0unjy268hjx566x98c9qfp68my
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIQlpmM2tFdTZOVFR1dGdq
            ZkhyckM1TFJNZmF1YzdrVWlXMVZBZ0tQVTA0Cm5GL2MvVEM2cDUrOXA0ckpUck5o
            OXlobzc5VXg1a3hJNEZrenVWcmpEUEEKLS0tIDd4SGo2YXpxQUNCY1R0RGFqWFEz
            S1BadWZKK1U5RUNadXFLb2Q2NHA3cWsKjUefm5sCKNQf7Ppop0QYRK6WsXfTQ6ua
            PMpJAFniT2N58F3Q5M38vySvJicDGFHXZ+tWCUtpOamobx6HMDp0Mw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-01T05:52:06Z"
    mac: ENC[AES256_GCM,data:waoEOuyIqrbA4FH1rj/YMXjKfwb08q6++wl9Fmu10hbWjqFji30/xFwxCWMCce4SXzoR+SxQT3z6hUDZao5Aan/L03bpgkZdKq/9U4GdH+fmeCk1MM1eVitHc1BSd7CUDhFGa/1xAMfBgbZg5aG++ohLZiKidlRscVhb1qNOLAo=,iv:1DLDk6tGGxxyz6g+Q+fkxN2mOxz3gw5g8KkcY+9xPJQ=,tag:8Mkk3w/0e5JKKoadhj2ODA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
