apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:wqs3fYWTnzp+DZS/JfITeFNFHpvekMTTw704rFIfJl/2k1CAVWSfHuTnXylrC4XfwvXBsoesOoy6nTCNE1y9L3zhfzulSSACOvgY/3vG4om0f9sUPsO2LZCejPBREnUfZFye4s3M9GoYhFJlhSMjRpGQwFmGzuj0Xc8TPIURVBu4vudRp9KaFkzrF4Hpn9fWaCVtFqTNph4+Qhjax9Tm+2mCk+io2cJr4qjsD1UWl/Aw5oS2civvriZMwygw5jtTGd0BdcKoL8YNlGKO3UgKZNMTdwwWWH/+tWo/o9wF6JHtqnPEFpG6zcfcvcAnr4O1OsQQb1kmQiB/VKGEZQruq6mtNa0JqTxgMg5kXBr4nQciks8kAwfaxWCTpCl8+SCs,iv:MnUo+HNqrl8DkjHhIH6aLfjiHyGdgp7WXCPtnIkmtKk=,tag:QM9nEyXbLO8sQj9Fo1KlLg==,type:str]
    identity.pub: ENC[AES256_GCM,data:vQQC4g5xkjPWCZLNqNU6RgYXGay0gPlzXY5PXdB7166hbel5q2bI0iaKUBrLpNDHVRIj6Izv6SqRUsGLfnzA6WUgCx/7od4fEFYAcLNHgB4k9vyEM2b8ySCWAKT5EW5tLirPeVzeyJqmrC4WqhC5Yf5gsFw3hcKZJFQEna0davOp7HwqMrmQtwJKrIisdNH0Hh1AZjBdNjooMUMmphmVElKSXZlhXYMZFVPwyOAYH9x5ocf2Z3k4Tgj6HRpd8/E+4fWDkuUpK+g6Z6PMHg==,iv:EdojLv+09yEXf31EEnhLd9fxJLgTCTIz6E8jB0nnP5M=,tag:+prGwiGSPbdlKs1qRZpFVw==,type:str]
    known_hosts: ENC[AES256_GCM,data:6cUShVsyxC8zzg0RMd9YAcuVdtrPpn0NO/DM2SIcLflliXrY1mJLphwoRzFyNU4Xs0nDco146zjxs1YkhISpFyqAz+OawKzpBRWpsBvfac9Y3Co2gJVeJXmpNKS6Manm50MTD0ufUnoh0Xhkv+oZsGXcFIV242eI77UDosB7bpYW6BBSUJB8PkQnDKeLDSkCSa1vZ5RB31wv6OLg1W2Cduc/5iHegRM9eaFh,iv:yLlW4C+MwIO424KupuODXsceYfZBxZqZhOnd7dtZxu8=,tag:9lze62XIe8OaLqwU/7IlvA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1n9xvc8p6crcha6nylpszt2cq2ywpgejy0unjy268hjx566x98c9qfp68my
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBudE96eTBrVnJVRkFpWUov
            V0tqSWJJcGdocTJIcExISFB0Vlp1SU12WW1BCjh1cXlSTkUvQXlNU3FwWjNsQkJQ
            NDRqTlpXZXg2R1lLdTRwcWhXMk9iRVkKLS0tIGc2UjVwdkUrWU1CWlliQ1lIdWFF
            N0VRSlVHSWtjZFdNR1JGUkN1S2NtUkEKjPbqfFEcHI71mdTc8/UyMpkITfpnluUf
            TMld4t4Dw/R7lUa5BYbAJrUR/A07KuNmfNbkoYIyoCjvyAjzEvgvFQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-01T04:33:47Z"
    mac: ENC[AES256_GCM,data:kiSCSoBnHgn2IQpIiiVQvHdR8+303a+LII3CKzQHDdaAYyViPyANUpmQ6YMltzydktE0CA4Dp/YFpjkqmxF2quQ28IyGdhrg9Y9cALuGEZDABi7CmJ8G59Czm6zHzxZmU8tJamZNdVeoF6I9tmsOaOBoT7NPPWYwPDFCix6+XpA=,iv:jMKFFZ8NYFQ/m0uLHXpQFNA+DGixyfSm5CaAPpD17SU=,tag:y3owzt/PZplBJivh4Z8t0w==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
