apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:2C0QUkSOcCLxusy+qLyYDVgQvqjWOS6GkygQZGd8+fMXRdslqXJho1joKJbriOYY6YXkdyP3v4w5B456GtM5Mpp36GoLLmXcZR35reauW/4dwwnhQWIi9wPoBedra8vpKCg1lwCMhpxXoIXF7vDyWT7VXra+v+gvuD5JBcRYYWoO95ls3Tt7M7P2s/pFLHx3s5ycUbJ4i4JF+yY2KpK+WBIOnJxHvePp3NMhkAqfoz2BN/ns4NIV6T/vjDapS0K9e4VtJRzaNzxyseTc69Cw2oFoWbN2a1jtW2gpcz6vc4wr8oMklGSkQ3lzWMr3T5GDlv3pU10INgOaoNFgqY74/eUW6qmhNtlBObFZcOGTH9ZArhps6ttYm0aGpNLlDjDb,iv:6XT3CToQ2ouOPC787lxHTLd0+IoHX9yGpGxelGp9m6g=,tag:R+rm9MUMgYAZovMO5iz7Kw==,type:str]
    identity.pub: ENC[AES256_GCM,data:08SjgUpRJsUUDgIw6kEgjk4Ec7CaHJ4xiSTCiIIi/NcYm7AppNi1y0g46IgfslCl8jMrTOZpSWRC+EsbEENSp46E4d84BBNY1a9MUGjnAOwG5Qp1ZlVpRrdseOwWIz8LbTQIzsAmBbmxvAYWqY22T17QWusiMzBxbbDCvPFn1uMES9zrO9ZHSuzhZzozpt2YqdRlGcpq6L9XsLMKguVTzyY4EqWiFqj6pL4AUQCds6/P7nvrTeulgzwMeZWE7Gn+3enXF2Sm9Coj4CD1/Q==,iv:ErxChV1G8EUr1ariPxaT+jg7ud+Pl85UBJFVknj89X0=,tag:b5HBhU0svI8BWfnrFa42YQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:juQGTGVOKtTKWxyeesq6gbJr/23FtuuJcfw243m0W0fzSHDimidKFvwzXWl0Uok8AKqwi1fRdDL6mB/rOoLH/hM4P5dUsRb6FrCTgjgJNGmxlfSMUdSG548VvcA3wTfUlINQKXcCkVTQvDRna1wj3EZfqIoAWokoowQBWUX6F1Ztm/sKfqkRi2OxAzzegNkIe5p4n6V3bbTYYNFkPnU30+bnd+DXii7PN6oI,iv:RYOAC7vFNuf1tM8SmqluSRzDQCUw189G6tt5r+AuTSA=,tag:x0RX/g7/i94LdTcnlKRawg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1n9xvc8p6crcha6nylpszt2cq2ywpgejy0unjy268hjx566x98c9qfp68my
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlZGZ2Z0Q0RWpjS0ZnS0Va
            bkJ6RVhDc1FOaldWNXo4QXBXQ0lEYlk0aUZVCmtweG1ua0NFRjBuV0dYN0FreHI2
            Uk1KWm9hWjcwcUg0ai9HbHlERmY4TkEKLS0tIEN2M0lER09YTWtWVnVQenRwT3pH
            NUVVb1RuTG41U3oreG5USUlmZTJtTzAKK6nk2BqEkifLBIwJZhjq8Q8zE44wDkKT
            ImYIJgPK1YVRhLCtMfiJcZAuxJxU4VW4nKeRDegLxEYLJlTkLiemtQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-02T00:32:25Z"
    mac: ENC[AES256_GCM,data:D9K+i/hwe87vEnsHP53aPxw3kaGDce3QgAuEVSH7M1oqXHTd8nMK2v/JzUo9GOvs+anTPtb8QfLuRCm4nK0JQTEUuwFXNNX3W27t+kBGCHHVkEbjGPHnihKxJknmSpBhn0uTaA6VBLAbeG7UPeMcsre3v9+H2ggc58Z8aulUWz0=,iv:pHQg7hYWJe7044kOklUGgm65JBAywp5YX+nDbsqFBqQ=,tag:ivA02qcwqz3xpNL3uhmJIQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
