apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:83aTexudVnHcFMImO0QsGbEhZxu1UwYqo6XoAqW+nDnAjiJd36xiEQoqCr8kZPvJ2ttflWsScMu0y49dEY42Rib+B/GG6rYXaaQLc8PnkfNQfGIYEn97Cu9GCcNf+iIlYX08HLLNmgBvejWOHYbm2bAiClOyYWLEEjOmMBD7o6cZ/7YYE8MmNJyNcVvbfLvGozf+6pUXqbCm7hQxHwPDv4U/bsB0NyMPDS7G256eHVCBA6l0ZGNGVrzjwq5CWCO0ICHYlxNKbbukgi+dR25GsRexeqezPSlRmfuL1edfOTEnqvQv65yXC0KPa9/LD1p0UWWsX1saiOxX9C/QdwWZ6wVnToKx/BWsLri7T6K/G3l/WTPJhs7jVaUJqVXeiM9O,iv:s1CKPM5X6SKH5RYlOLZYsmmnj5TrGn+c4NufzyY3Gug=,tag:HB+fby3llEOeCyX0wPoqqQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:QVeRVS4p92VloF6OKo2y4Q74z0t8kPLaUG0JC2bB2SgyMATM3fPAQ7s6Dq2N/LKVWhPDzamsYonNgn73xETQHanS2EbREdAZ2J4eSDyQk0OctMIWFsYj5O5IlXdhddKa2e2JbgLiqmwUniZG2T1T1jdd006i6zTz97xqQZMWlb4YyaHN7oLSMJhphXI9GtTIv2Vn8Idwh5PiYj9ZZIZsVfLZ/HgjhXA/BHgjbIirjAvR/tZwa1LcO22BMuIbxTw+3PJMxorpa4srfAi+ww==,iv:cGndAlsgzgowa3r4goTVCRQtTDuEwYvqMZO2VYmrUbk=,tag:F9jCMhIAzHl1LqqA7Z/YzQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:FRLVnTaNtYbHrbm1L65Npft/HB7rs/MrUr2iv4TndcAkwQUMKTqsqZcnkRsLewL0cYTg19vNTjYgMusokwFi2b9zH98Ka+cpqnBTaDPjf5E1P3dA1Tf/8fzVQWEFTFQaeN1MJJD+SxXrjXcTq6MJrHFki7bW7GOgjm8SBAUghGnIGk9rMpFr2fl69gKtjcWDXOz7XnOwPS5AehDWjj9iyZKYDeeq5IKMCPum,iv:I+GFnUyl1L1P4KFjcTpDijcNQ5/71jyzSW9hEZzHDQ8=,tag:5z1xdNuZ1+8TPQ6vElbiCQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1n9xvc8p6crcha6nylpszt2cq2ywpgejy0unjy268hjx566x98c9qfp68my
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhM21sU0IrWHBNUEF3TVFk
            Ky9nT3NrVS8vbjhwNkdFS1NDNVVKNGE0YWlnCmEwMnBKdmxLQlRzaFRIUVJKNVl0
            eXZaOXpFdzVTWWxHT1JnVkpqU3ZiS1kKLS0tIFdMSytONDVoaWZmeGxPZDNIUm5Z
            YnZsei96alhEUHFHd0hiTFFRNEJYaDAKUt5rTckTW4LVoVXl7zBDWv9i9vLgMYdF
            27CmpSRGVbehqf5M5itrOvk1ILZVcqyo9HDx+y/2PytAC3QXulgKIg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-01T05:30:01Z"
    mac: ENC[AES256_GCM,data:CU8akN1tndd+B+z3jDjxGSTS8eV7sdUEPYMwLKQnay8tzP821r6TxR6pxORPNcGoZuSAfWVXEhFCyDiCJAdu4KyHBelpnXeHAhWpGr1lxqYeO7z/+lTqTKCUv++qrO+bjFQph/EO1ITdJZZLOCiSG1+bT9Ua8kakPkHzPLeIO6I=,iv:Q2S+fFF+yWEb+kMGCc+/St0CA7FzOJcFklyxhEztOpM=,tag:FyvAe/GDyRpnc233ogJNaQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
