apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:qeYTdsVbzI+JBhOo2ek/8SuMm4YOa9OcASRjvMTySYbkFRYoCUaVD5YRjQmEqs+O2twY3T7bcey9kefMYWuPvmpYe87tJoq4kHJafFdk/NRi9tQEU3j4IFZ4QCIXcCNWf2lV1mMmCoap/xfd/2GqR7wo6oZq8nY/QlXKKVq7soEmZ4qXIoUi/yWp27y0Z2+HRN6q7w3fRCYinDozLJMkkPFEubc71rs4euGKEdV5QY55tNlCnk8kjq3jmSclf29Uo/vn9bDx460DsE6ruVG8Tpro04V/sNuTOlVrUnLDJ4P8Tv16lN6wbDGnw0d1arkIr17Y2jTBdlWT01YpWT83sIu8Ntuz84cpJOWX51HeQqeJKN+cZzyfhRmgaIdQ+a8z,iv:A1UDknD+SZ9NO8F5C7Q7TbEPmIUvJZAkK4Vd9Ruv1uw=,tag:r09nr/PSCOmRjLxOXlmzqg==,type:str]
    identity.pub: ENC[AES256_GCM,data:48nIsaqCIHLQyye5DG/G1Cf4dFvsobYScihRe0Ih3SY8ZAdnBVYMwTT36ymZEo3jHb8aFd9woB1grFD/EkXq7OhXV3iqBp915re8GOPAQ+HGLQmkgLe1L5GejIB2z6jgiTQ4iqo6fTPBcvKg/8yqeglqSQ+3puICSt6cQZGVoJppsFPUwrSd9KGxBkvQH70tXMbjG4UZaIeObeM3pjD0C4GJewJBZdlzplEhJSUIqqW5Dr8GTZVoD00Lgsg6k35LFRkjDUHyTleAdwTpxw==,iv:1PZMN7IeKUQFVmdvaw6AwRWTSy+nvc0ymtLvw6lj2xg=,tag:U/qd/PsIjnifHFHK6rmqgw==,type:str]
    known_hosts: ENC[AES256_GCM,data:fGeo22n8XA9hDY+qsOGV+Dru/4Loak1iEi5QHZpYPH/hBtUc2iGQ+yLLuuRpbnvlK2JwNMN3H8VMyMpTivlMc1pgqejhwWhG5Vc+wVVRPq8LYH1PrbjWXHXvYbeBcQykWfgKndO8wvw5bWx4brYa8Yhnk/uNJBovIRDbiBNPpX7eRCI4BKz6SriqYrpIdH3Yp2ilSNRAQuEdZ1+je4DYqY9UaKosrh7E2p/S,iv:eaM1saJ6gOJSUWPFO9VaLlT/Y/PNqqJMQDstjjxA0Zk=,tag:X1w/2vfqkqTzymx/Ou8u3g==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1n9xvc8p6crcha6nylpszt2cq2ywpgejy0unjy268hjx566x98c9qfp68my
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkWjc0UkxVSmppRWU3SndQ
            NERXNE84Rk83Z2tlQnBseGRnYnMrOWdVR0dRCmNqNW5ZRVZta0UyM1hPcnRBRWZP
            ZjNENmdLalMyVm8rcldwdXZkQktEM28KLS0tIHFqQW4rbERwa0JXcTJVdEdidmV6
            Y2NsZTdNMmFrQlorQzcrQzhjdkxVbUkKIUOrnGsLxtF8aQ/X5ZfFZ81vwAfsxYRi
            4AMll5ylzn2QIthrGjjxKSovPaHgOXeSPU9UTDd9Q3mXHMA8SXGeYw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-01T04:14:23Z"
    mac: ENC[AES256_GCM,data:LQqGv1DiZQSERqnUX+qy42RAPpPzqro9jlaNl96xkZciQY/IZco8XwtgA/mO489U7sZxwHtE3ioAA7aM5g0iVKAojj4gxS0gVeZD3e1lfpFJMDeZX/7V3rTcA2rGA9u7fDJYjrp96TqaNtRmPLd5zaOpg521iwaa6SymdXNzOKY=,iv:JUc2iteUE074btkoW/cNHNc5R6WuTvoBDoy2G/n0Mus=,tag:W1Pw+JVWtVkm96Iq9SPEmA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
