apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:viXyfY5rAJk05AHUDfdFCiOH90Ko1sXh78iJBWWNbLBl7yu4wc8KLx0iHozUAblUGq4wEAlXGlhvlcnV/fJ5RW6KF2VwGgof5h2g3jDBwKSzPKE95FEAUBE/7ewCfg6T+0+bETaKOgQb20vTrt8go0/QbYOsNCBuo0vqJiFlHCM9J3usfXuu08sYxxMgazuoS4CzneX9guHIe2Y4pAw4AHBypG3ahimmCEPu2+JioJ+IABYUobJTaVL16YV1+W81GN4tYOlfH+jKAYpOtN74iZZwUyx5xabD6tGP+cb8FdUC0vcDnvUcruh5j65CBfdwLWHQXzs9m2tzMs6FVpb9NArL1KZLVNvOkaZRZFd2DYQ4ZriPSbUOdyH5uNihk2Vd,iv:gk39ofyKtjsRUa7mWCtUQivuu5ojAnkb5bvA0Kw2dtw=,tag:kQBMXExBQBvVpa6A6ghiqQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:Izr9AYt647ZoWw7OF1ovdSd5Jj4zl/8LQ1uOiiQssECqkZ7LOjQh4W5CqB7SpJ/RCXo79Uqz5WL9B4jskmU1opwPdpcaYrggysggIfaDeRtWJwArcPAHzh6n95PX4h3rnvoE+CIJUgC72qSDr1ynEDJt4mHAg1l9m/FkVLTNtKekIBD8PZ9F4tmgg+KDsGeQf0GL6SUnzNgYWi0lHV+ah5QIxMX+I088uj2W9n8LByqWk08nDvEX2ZqXxwMpFeJG05pmC0REG6tU3Q/uwg==,iv:gnVqKcdteVDu6zpwUGtrjw8Jn95mDnpKlQMA2bbF0/0=,tag:zQPzm8HVsgoaki8aKIp1Og==,type:str]
    known_hosts: ENC[AES256_GCM,data:YlnonXaBh01VRH02mRo7NfkJiPw4oqXCVvjGBJ0O9mEwVFBz17mIYNb9P6z1tWKLsju3JPg3ZDXRB/4TI1pJIRtHslwwKk6drOmN688mAiEq8kMqPNh3jH7esmhs9u0GlAI6udTdjbzlCbQ297+Ftl2guZmX4d46WaWtPShFCvayVQQc3kQtn0AsBjKWPZL6wfspzx0qPHcA9lQ+fUbZ14l83457XTh3KN9P,iv:sBjlttm2woidB9XszBQnVJLZdrFYRhcct8BVtvJytVw=,tag:hHEjHniWjg10MbNdsmngig==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1n9xvc8p6crcha6nylpszt2cq2ywpgejy0unjy268hjx566x98c9qfp68my
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByVE5wNnhkemNnK3hZUW1F
            RVVLZzZJVllGUmhQMjE0NFNPQzdQZzc4WURzCk42YS91V2krVnRuOG1jbUZ4MG5i
            aFBlVGdmbnd4VmM0NWdOZnEyTGhYZlEKLS0tIC80NS8xNWJtbXJzMUxYSjhUYi95
            VUVLMjl1VVJYZVlpdWVkR3kzS1BaVTAKbeMeXi2wV13mdlpHvXE4gHusHNVqFlIJ
            5SJS7rNH3l6nm9ajVB+GZGivPqYkCocjPzqFK5BybWZlaBvr9Sm5gg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-01T04:22:01Z"
    mac: ENC[AES256_GCM,data:618ObcfVspBBtwCAx5w13IYX8vD0Zld0jXEO6JuKCEzlXsvRHjgDsuUaNhunrTqoYPMfuF1sZ17BQ4JR/o4P4fhOvjPWmFIfqHZKEp2HGXf9K1mr75Lp0gfdQewmiWaGcogIoyvqf6UuYujdn18Og7Nm1Oyh3Av40/InvE9Ry4E=,iv:kxRi5RtYA+e0rlg2CESeyVbL0W7Y6oz5Y6QWyaRuWvE=,tag:Tp8invxK9Q6gmsDfvL2mgA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
