apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:4yT04HImjhlz98MOvcR8SA3ffrxxxvhCeFLs4+/JWfEnRH7mSyEmBGGQTK8daUb2QDJ5habPNb33Yg6hx81Usgxm9nviZg4jUZHT4IOI7o7sPxqpwEbMkjsAKcfhkIVwS536HiVKXP/QBrrvuI0gNLJ38kBVdxfRw8THpBtwjCJFnAIJlceLRKlNBF/XsKq6u6IEZyBb8550i9zp8OlcVkiFm5YmWKj2plltbIi0jMghKNfXU50mYRR63hRGVL7XGT5AdNbIKp6qQ0q3sVikVbDFxFJhG8yRXDGjiysNDEO6Kd7wbrlvdmcN0iOP3jZcIlWLj8zM0Wu+HDR32Mmzc/bHlJLoC6fKOlpdlOb92sEcczlXlqKOsFXknD8ZMRbK,iv:zM5/aJtTgye0wc0S1708gvRi1tCdvEmHUDFUfK4sd2w=,tag:xHqwf7AtstUEGC32AFozYw==,type:str]
    identity.pub: ENC[AES256_GCM,data:lpniN/EjJrjEqUU4wjIXVuTWrFrdhwmmyp5A8qIMqIIi/nzBvo/E5664GaLQoUDfqGF9mNXJmRKWbOnk1PflePXy/G/VipNvzu/MKOXmZDuCArsr4zH1U2kcttEIWLpEJmWhxSKfARvGbPt/ZUYUtQpnu5PflRAYFEdjvlu/9Isg8TWWRIQSCPxkBsfnrexLJav3cJv3KjK/VQgJGDct32zuwKu0+T9mkwEKHRqzyhvTTsK5SMNaThf1bGTEc/gJf0n8iNnOkwVq57NEVQ==,iv:9/tK4NR0VZiYdPStC2WzBMJeiRcOUARWOg1szSwx9AM=,tag:2k7CcG4ePZMoUdLFHWqQJw==,type:str]
    known_hosts: ENC[AES256_GCM,data:g4uomI00JqKp0ajRKlZRSF4gyJtCztOCi1Pmt1aBgVLEk2Kb1Rat88AsNCebM7H/9sJrqmH+N1cmbjnqoDXGv3ay+0NKrst8WjrNXCHmt9INWYPfF0DqE42er0D5P0o3sK6ie/65wTbj2RGsrt/S7oKM+ZzF236AUU9ntLY3nbu5Vab93zvCF3FIOyDngromwCru2/JtpuNr3AZG/GPTSMWzSrIkb1YEbDsy,iv:iy9wMl8WPY69DxkXOkwHkBHnFfee3HeopM4K4A6U/ZQ=,tag:mxuAu06Qv5eb7w4xhbvZPw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1n9xvc8p6crcha6nylpszt2cq2ywpgejy0unjy268hjx566x98c9qfp68my
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQdkgxYzBzMnA0TGlGTzZ6
            V2lzd3NmZDB3TzhZbkdwN0RHN1ZHUTZ6TEF3CnRHeWIwTm82UDI4NHFVWndiWnZu
            dmNMZHFwaElKZVhQcnloOEU5MXFXKzgKLS0tIGJCaVByOHFsaWJIY0l2clU0VkE4
            VWo4aW0xTGtQYVk3WlFNcVlKaS9UTDgK4NfNeoVqZK0muJnD29nQKSqHnM2kAMuu
            6ozpIrXyL6SD+dbDcY5L32Clx26wvt/AI4+zj4huDeGi2pSWjTdODQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-07T21:47:30Z"
    mac: ENC[AES256_GCM,data:6JLbcw+UiuptYC6i161zv9aPz8/ZysqMeee7dHThxbgWis2cjIVEWvhTAm7FcJFYKnkdeaZuuRGGJLItiSMWA9SxmSWPBczScSI/JvJcDzT9VQ19Y483IBDCcpFGLc1inCzQ0sSHOXI9HqaN4ORpHaNjAVpE3HVrMdWDpqxGda8=,iv:ypp896rIF3Qmj8+Cm5mtW2CjJ8mGAfHkBJF4oV2D/TM=,tag:I6aY5RjQKFbhSOfcUGKTnQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
