apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:WYrru1S2RGtMg9dtZx0O8gI00CdZ+A2OBSrKlWQ6vS40wzrFn9k7w9fuf14ErT8EqTCfOr9RfUoGuuNQIBiMs+RxWjxja8VHmlXU9+y1IF1gi9hCahCueFJLuAOssK3lWcRk5VSTQbuFhi5YDfmwwXjg1Hy9Weyc3OxYoXEg0QDlBmZekjsPWMFheOb9WRzcHYSduLRSnpwpvHTssDVG+CRx+Z2v/yp6dbvEPFxvOKcbBL7oTMaN8C/UD+n8T3I5+ru4g9dExr7u2eFe7RLmEZfJ9zvBR/mzJEEckdt7sD7wyOh64N6yO8CojZ8gYzALya04ygMXhLcl3xa//0ZNlBsbKK0Ijz8sqhBEBlg6SHehmawkqtYdjEyhRduy15Dl,iv:YMmYoUctpV9vBRxlraeyAXM4cBb1Iv87CSQJc5rMFzI=,tag:rhnwrjJHNmpDBcla/XmLhw==,type:str]
    identity.pub: ENC[AES256_GCM,data:nFOC8EnbCGAtbfuZZhkqiAmgKK1wP9NOMuJGDWoNKhsELxPCUgi+g427m8uO4p/6Xeb6gMilj4FdiFGCjdV+1mX+aI461JiPRZXnaO3O0R9b0BgjIRa21r/FBJGwe+eUPScCbpqx+kWN2TPJKop4ZauQBvLh11gSFhUWMc8FdoNnrKYgiFDD7zkqtHsEcHDQC3N1V79EgW39J6LnJbM9AuqkTwkw0l9/3AM8J688DyDT76r3fo+9BDuM3tiW0DMfnl536rI4JIoE/GRpGw==,iv:4KlGHo6DQm/5wE2nxTARtA+Ile9kQpwzNEEeumyflFw=,tag:HRgfUWyMxL1Z2pCFd33GAA==,type:str]
    known_hosts: ENC[AES256_GCM,data:Lpfay/W+HdCoSrQSN4j+SPKq7jMPBBG8qB7M06qrk7MGoYdQegmkr8Uo8jOP/1FyROW4fwczrhaGo6MU4/1iC6xR4Xz/DxDL9r6AbvTH13xTbLfdCh1IHpM7LSh+OCgMzSes13MZfrsbT0M6CL4lu8E9I6KiCMTNXypZhl7DrIe9X1jUW6Y7UVxtIlLw8rYnLuUcc8NMAxw6AhK6lA6jMsp0Qv2egE6240qB,iv:ts1H3keSI6Fjp7ZbzipFbA3DjXVgizeKj6EIJC1v3qo=,tag:CuvMZ3riUjjOPs+0mGWc3g==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1n9xvc8p6crcha6nylpszt2cq2ywpgejy0unjy268hjx566x98c9qfp68my
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXNkVOVFJkRGdnRDlwNmMw
            MVcwQ093VUVaTnlxUTNvQ1NaaS9Pdm1VendBClJtMHZ6anY5enRybUltN2VTdHdy
            cU1rZnJHVFJ1Wmt0V3ZZeXVhUXV0Y0EKLS0tIFN4TVJMTXJHSkxtZlBnajhCZHRp
            eWhZN291VlJwVDZSVCtLQ1ZqRDVYMk0KYspcTr9TgJpe/8GS9ofWQn0K5DPifSMa
            D/nFp155NBNWsgNkGSCMtWEauCbRoBu8AaS7ATxW5Qe7obhjqgECjg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-02T00:36:12Z"
    mac: ENC[AES256_GCM,data:1Js4FfVBf51fisGVt1HSlGd1bjI4ht6HUfi0TdznoXjuJR0eA7g8GupjlwTlK7A1Xjkt9Hr5h+PzPqPARI1fxEvnhOQizxocBFAtU9H5oVKo/ckxepCoVbLW7oSg2SIXm32vDKUUWlSaNOR8tHWaLG6UsPDLZth2G88sIpSuFUU=,iv:gUzgF/Zes2rtSERy3BgTexH8pQLWjMnWRCVfEhXKyTw=,tag:NCXhjpYPNIwOaOhHEMryKg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
