apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:II+C0QoGn0ZaXLgiIjNnEDroTuEw5UniPVTQlmdye90za3xhaDWrFzbt8y7VBUI1CTDDhfprvIAYu5NL48h5GBsT7ONkjMxbkm07BfrG4rztBwwsu6kHrXACIiDbgtKdOlwvRvS7oDrfXYwi2bHqlZZwxtFWNMhVNTGQI++K3tirfpT3I5uKj1Fgwb6s1OBKg2lVPU1jFEywUrf38tDYDujq1wNcoL/+MwV/0MEob6UUsrM9vFpgkV1SSaMpip7VoPjd/gxH/2ongZldO7aFqesubraxlXkoCawTVahdzA2swu3aSjGEwVL0r+MdLYUckFFCniH8A+RLSJxhj80Zujng/Y8X7xn/MSz32toc7VyeaxS+bI50T0aRReS9I7Ia,iv:1DaNb1drvgGicxvpexaKkZoVJZxoCjU/STZ1KWK95ek=,tag:qSYy1VnO8xMRSK0EfHpwRw==,type:str]
    identity.pub: ENC[AES256_GCM,data:diGqqdfC9d4+8uTSRmdh65zV2ndGWa4ZWyXydUwQGlr0c802yS0QAZNcPNmJWr8hRogE6hZXmt7TjaGg/E2dkI1wVdIFJAnVyiz1YB+l5CfmxQ7VgsyoiRiSNZCnFuQTpcVWQxdxYNQQPXwb0Wbcq3O3VFZOeayX95Gl/3SDG7tqMswgZP+kKnpLB7/Gc9q0R4JqbqtJU/u5pPQ79auQ+mlgM+us0PdcC5NZv2gmhr+fa/z28o32af5W2xf0LroZV8WQUyQVfx/kWGtjdQ==,iv:3gfOhQNkh6HGWoKAIILykQVATusA3QkQqfltojzyO9c=,tag:nqO4MeWk1svA2HwJ48YvJQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:RMFMCzrhOGqbJLTksBBWDHcN6F7R8sKzS7QvGfAakdgO4n6GKUcuENOZqf5qmMBYiSe8QDx9g2d3azkXj3E+oSPzgNbP4zFK7h97uA+lXhO1e9PF83+9RQlkpkdVWxaT8m3DjYrnjGGKMUl4U3x+eQ5BpeI08EWyPy45guo0AkyzhkQYcGujmdz4IT03e9IpEGIncPSf7zz8QRxV7W47V7Eckw1oNjaZejrn,iv:qqtPSU858zhCUWYhol2vYbyI3X5JlJJvE+Vz1knCZAk=,tag:nUeGmNrBTInMLQexso5okQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1n9xvc8p6crcha6nylpszt2cq2ywpgejy0unjy268hjx566x98c9qfp68my
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzcm1rNy9LS2FnRDZGcFJF
            MHJlTExjU3JSakVhd2dlSEpQSHhxMlJ6bEZFCkZYMndNdHgrbXU0bnVocHltbGdQ
            RlpUN2Ura21WRHVBaWFrVFo1S0l0U2sKLS0tIERBYTJDc3Y1czBKbjB1T2hTQUM5
            cWJqVlB2WS92Q2pvQWRUVjZHMm0zYmsKaSE/e4biV7tzds37bmiI25A7YbmPR0Sg
            jTDMZS3K+cgKiqJzjnSD5mNSzrQCBJrT8+MqyNAuSnqOyF6hB7WCjA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-01T05:20:05Z"
    mac: ENC[AES256_GCM,data:li47gXbYZj5hhMZansLMdibvHLAKjQkVshMXndccRhpyFsCLqOrPplOamT1K68ICDHcdIXqvezaxiW34S8U51LYzrBcUDyEcOcxt7+4AQzoJL9BIltxgco418E1y2j5i9Gz2XK/cwhPmT7uqUtULVTHTlsuOs8qSyVvJnWIppb4=,iv:AXN+6JbQtspyBUuJ7NH55r5iTrFhOhhs9EC1sbGrus4=,tag:XqlJ64N6ln9jQXZyD0XZRA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
