apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:R7G/7TPyUj66GJWUzASkB1iLkwmOggycL7/3kwFztLCEEtDsM6sq3jLpeV1RQDz+2V/gZ8OPVhloHlDjJWohwDgCr9A1NvOhhBUdekGCq5rnNLrBzqr9Ij7p+c5lyXlfpTevLY7CnBDvtqf9e2LIC8emADMwbtnppjIkgjITRl+D8DMLrcHGIvnlRy2hB0Olte4gpZDK5tcGFWQX2P+pUwYE9GAXJVROvCnYhbkroRKE2Az4EIzH4VTV0ilrTgUy80BjNLwnjTP2UDy6udrwgAQjS8xUzlEsBA4RCqPBdmpVs5R9OWAhl+kHDgn+0ybPj9x3yUkhya5eSIMAN3rAw3GxmiCZeJsLSszNFJ7iv6I15lJVAsd9TuR4MFMgg+0k,iv:4BSoSinoErIfpw1RwrYOlz0oApsXHWj6PcAvr23iYro=,tag:GzbldPDQz60aleb/9d4kVQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:qtFzzIC4mgGFr+0kau4x+Evu4R1Ynx46qguUu2mrL+4zz6aTGwxLF0gbsvPq1VMRvORUIyH+RQeKS4NHS6Mzmkww39Hrwj/PAtPGOJ56k/LKTAq1rk5OFd6ib8QUZdtF8qlmTYpqFNu3V3mhqEVfdmWqlYT84qjIxGV+w/aOq7j6tk2+5B1o65ibarjypXCHJOtnlfjCN7wvkB4x3HE/fkXcq+auHbip6U/BJK8Zt+DGnbOMPcmc8TqQ5CqJw4DxRBw0EoOZg/gR/3uTSQ==,iv:X2hyKosHB3o7Vjttu6IFa/mT6n2VGyq3Ct1XZVgArwE=,tag:q35sQAfVmDdFeBygUhyBEg==,type:str]
    known_hosts: ENC[AES256_GCM,data:ofEF7NwZPRLqQoIXbvK3geJDKt53mgYyNr7Q19hBiVAxjH5zwSc1/NgGHCyfkhCilTwh57mFqScXaivmnO7nvXZAZUx6NCY0072CH15PjvfzR6f7N8Vyy3igsgJd58ksFUeYWDsz0s2e+RC26S8fOgRzEw9nEBFSAP3dR6lVKOfMLhMJgCZL8EAaMPlnF1e3aAdPxaRCpooEoo5u0E8lQ3jFN/70ddREbvo1,iv:K2dRfoEjLzHufN35N2U5KgL6WzT0ZcvU9VHBuWjOlmc=,tag:E+TkKdf12IEG33ejnKgZQQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1n9xvc8p6crcha6nylpszt2cq2ywpgejy0unjy268hjx566x98c9qfp68my
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6YkYzbDhTa0h4SjYyMkdh
            NkxiZUlTMEl4NUQwcnViUlQydy9iS0xIS1FJCjR1NHlvejlYcXdPL2xWak9PTjhp
            Wk05RjZTL0RRODRBV2o5MktEM3oydU0KLS0tIDZ2UEpsQXl6MFUyUXZQUGJZbmF6
            bUZBUVg5TlBBSlI4eGlTci8yYWpXdEkKLvMu+9wSpDkjBrLiflTQIl9xV9H2PSFz
            hyWTXM3XCbfYevsPojyZcvPmVXM799WcF9WnfH3lVBpVvrUKjYpsUg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-01T19:35:55Z"
    mac: ENC[AES256_GCM,data:uNpNGAnMSbR5wzu5t0HP02udaKB7lOmlQ/O/T59TLqP/Ow12KGtZhff3uc8WKPLcotjTtKsDekEo6BRAXwH7XSvWoJjGINQmMxmyul9wvP64pcbtlEdFrITBuasSk5fRTf7PJgkTceQUZHsZi5FmkBr7+cysGNLsqq/2a6nDjco=,iv:ugXCnxZ0+IPrl5zfeBPbXp+QB7cj0mUzQfnapXKW5q8=,tag:ty7bHXgPc3sXb6kkLGtDCw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
